apiVersion: v1
kind: Service
metadata:
  name: nginx-api-gateway
spec:
  type: LoadBalancer # This will make your API Gateway accessible from outside the cluster
  selector:
    app: nginx-api-gateway
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
