# Use the official Node.js LTS version as a parent image
FROM node:lts

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy the package.json and package-lock.json (or yarn.lock) files
COPY package*.json ./

# Install any dependencies
RUN npm install

# Copy the rest of the application's code into the container
COPY . .

# Expose the port the app runs on
EXPOSE 5050

# Command to run the app
CMD [ "node", "server.js" ]
