apiVersion: apps/v1
kind: Deployment
metadata:
  name: profile-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: profile
  template:
    metadata:
      labels:
        app: profile
    spec:
      containers:
      - name: profile-container
        image: alahomora/profile_services
        ports:
        - containerPort: 5006   # Expose port 5006 in the container
